color_0 = "#FFC8E4F2" #wtr icecaps
color_1 = "#FF7B92C7" #icy waters 
color_2 = "#FF4F839B" #cold waters
color_3 = "#FF336B9D" #temp. waters
color_4 = "#FF0068FA" #trop. waters
color_5 = "#FFFFFFFF" #polar ice des.
color_6 = "#FFCFCBB1" #cold desert
color_7 = "#FFE8E1B3" #temp. desert
color_8 = "#FFFFF4AD" #trop. desert
color_9 = "#FFEEEDFF" #pol. snow glac.
color_10 = "#FFC2C0BA" #barren tundra
color_11 = "#FFFFFFFF" #polar mount. top
color_12 = "#FFFFFFFF" #tundra mount. top
color_13 = "#FFFFFFFF" #boreal mount. top
color_14 = "#FFFFFFFF" #temp. mount. top
color_15 = "#FFFFFFFF" #trop mount. top
color_16 = "#FFB4D4CB" #tundra grassland
color_17 = "#FF9DDEB6" #boreal grassland
color_18 = "#FF95DF8B" #temper. grassland
color_19 = "#FFD8DE8A" #tropic. grassland
color_20 = "#FF7FB393" #boreal woodland
color_21 = "#FF81C278" #temper. woodland
color_22 = "#FFB2C484" #tropic. woodland
color_23 = "#FF3F8A5C" #boreal forest
color_24 = "#FF57A84C" #temp. forest
color_25 = "#FF1BE600" #trop. forest
color_26 = "#FF2E6342" #boreal swamp
color_27 = "#FF57823B" #temper. swamp
color_28 = "#FFA1A100" #tropic. swamp
color_29 = "#FF36754E" #boreal rainf.
color_30 = "#FF4F9945" #temper. rainf.
color_31 = "#FF16BF00" #tropic. rainf.
color_32 = "#FF94CCBD" #boreal shrubl.
color_33 = "#FFA7CC94" #temper. shrub.
color_34 = "#FFA0DE96" #trop. shrubl.
color_35 = "#FFBAFEF5" #bor. alp. grass.
color_36 = "#FFBAFEC1" #temp. alp. grass
color_37 = "#FFDFFEBA" #trop. alp. grass

color_100 = "#FFFF00FF" #error color