[package]
name = "worldgen"
version = "0.1.0"
authors = ["roal_yr"]
edition = "2018"


[dependencies]
serde = { version = "1.0", features = ["derive"]  }
noise = { version = "0.6", default-features = false }
#num = { version = "0.2", default-features = false }
resize = "0.3"
line_drawing = "0.8"
flate2 = "1.0"
bincode = "1.3"
#deepsize = "0.1"
#respk = "0.1"


coords = { path = "../../libs/coords" }
codec = { path = "../../libs/codec" }
constants_app = { path = "../../libs/constants_app" }
constants_world = { path = "../../libs/constants_world" }
io_ops = { path = "../../libs/io_ops" }
ui = { path = "../../libs/ui" }
prng = { path = "../../libs/prng" }
path = { path = "../../libs/path" }
floodfill = { path = "../../libs/floodfill" }






